### ISSUE TITLE
client-switcher won't work

### ISSUE THREAD

**Issue by gabrielpasaber** [ZorbakScape/JagexLauncherBypass#2]
I'm not able to switch from devious to Runelie using the client-switcher.bat file
![Screenshot_8](https://github.com/ZorbakScape/JagexLauncherBypass/assets/144850367/0ba8a2a3-8354-483e-b549-5a44cd0d8e83)

**Comment by ZorbakScape** [comment]
can you run this for me
win-r 
then enter in 
%localappdata%/runelite
and tell me if there is a runelite.jar and a devious jar file if there isnt you may have to run the client switcher again and it should download the file and then run again to switch if that doesnt work ill whip up a debug script so it can help me troubleshoot this better

**Comment by gabrielpasaber** [comment]
![image](https://github.com/ZorbakScape/JagexLauncherBypass/assets/144850367/b8999a05-33b8-4f56-9462-c2b96d8a5760)

i have both runelite and devious jar files and still, i'm not able to switch clients

**Comment by ZorbakScape** [comment]
hmm runelite is there twice so my guess is its reading the wrong jar file 
when you run runelite.exe does it run default runelite

**Comment by gabrielpasaber** [comment]
> hmm runelite is there twice so my guess is its reading the wrong jar file when you run runelite.exe does it run default runelite

it does

**Comment by ZorbakScape** [comment]
then delete runelite-default.jar and run the client switcher again

**Comment by ZorbakScape** [comment]
did this work

> then delete runelite-default.jar and run the client switcher again

**Comment by gabrielpasaber** [comment]
did not work

**Comment by ZorbakScape** [comment]
when you run runelite.exe what does it run

**Comment by gabrielpasaber** [comment]
none of the runelite files actually launch runelite

**Comment by ZorbakScape** [comment]
okie well i just updated the script delete your jar files download the runelite.jar i have put in the repo and redownload the script as ive updated it and it should work now

**Comment by gabrielpasaber** [comment]
do i delete both the devious and runelite jar files?

**Comment by ZorbakScape** [comment]
> do i delete both the devious and runelite jar files?

yes delete both and download the runelite jar from this repo and put it in the runelite appdata folder

**Comment by gabrielpasaber** [comment]
working now, thanks!
